### ISSUE TITLE
Multiple Repos

### ISSUE THREAD

**Issue by iteanjd** [sethvargo/gcr-cleaner#1]
Hi, thanks for this cool repo.

Is there a way to create one scheduler to clean images for multiple repos? This would reduce the cost as each job costs 0.1$ and this job is daily or weekly.

so instead of passing one repo, we pass multiple repos?

**Comment by sethvargo** [comment]
Hi @iteanjd thank you for opening an issue. The reason I scoped the design to one repo is because it limits the failure scenario and makes it easier for alerting. If we support multiple repos and the job fails, you could have some repos that are half-cleaned and others that were untouched.

**Comment by iteanjd** [comment]
That's true. so it's not possible to allow both? 
As for Repos endpoint, if something went wrong, skip the repo, report to the user, and clean the next ones?

**Comment by sethvargo** [comment]
Okay, but how would you "report to the user"? You can't exit with a fatal code because then the remaining repos aren't processed. We could try and send an email or push an alert to Stackdriver, but then the code becomes unnecessarily complex and requires extra configuration and dependencies.

My recommendation would be to write your own little code snippet that cloud scheduler/tasks invokes. Your snippet then invokes gcr-cleaner for each repo you want to clean.

**Comment by iteanjd** [comment]
Yup, I will do that :+1: 

However, you can still exit with a fatal code when all repos are cleaned whether failed or succeeded, and simply include the repos names in the error so the user can know which repos failed. 

Not a big deal, I will do it on my own.
Thanks
