### ISSUE TITLE
Support keep x latest tag base on tag pattern

### ISSUE THREAD

**Issue by luk4hn** [sethvargo/gcr-cleaner#16]
Hi, great utility, thank you very much for creating this 👍 

Is there a way that we can support to keep x latest tags base on some pattern, for repos that hold images for several mainstream releases ?

eg: Images built base on alpine and debian
Consider following tag:
- 1.14.1-stretch, 1.14.2-stretch, 1.14.3-stretch, 1.14.4-stretch
- 1.14.1-alpine, 1.14.2-alpine, 1.14.3-alpine, 1.14.4-alpine,
- 1.13.9-stretch, 1.13.10-stretch, 1.13.11-stretch, 1.13.12-stretch, 
- 1.13.9-alpine, 1.13.10-alpine, 1.13.11-alpine, 1.13.12-alpine, 

I would want to always keep 2 latest tags for each release stream: 1.14.x-stretch, 1.14.x-alpine, 1.13.x-stretch, 1.13.x-alpine

WDYT ?

**Comment by jalberto** [comment]
it will be a great addition

**Comment by nathang21** [comment]
I think the issue is the current options only allow for either extreme. 

When `allow_tagged` is false, it ignores all tagged images, thus not saving any space. Alternatively, when `allow_tagged` is true, it will respect the grace period, but delete all images outside that window, including tagged ones that are not deployed very often. This may mean that some tags are cleaned and no longer exist, which partially defeats the purpose of tagging.

**Comment by njimenezotto** [comment]
Is there any plan for this feature? It will be very useful!

**Comment by sethvargo** [comment]
https://github.com/sethvargo/gcr-cleaner/pull/24
